[package]
name = "config-pub"
version = "0.1.0"
edition = "2021"


[dependencies]
redis = { version = "0.27", features = ["tokio-comp"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
configparser = "3.0"
